name: Task
description: 実装タスク
title: "〈タスクの概要を入力〉"
labels: ["task"]
body:
  - type: textarea
    id: background
    attributes:
      label: 背景 / 目的
      description: 期待する効果
    validations:
      required: true
    placeholder: |
      ・ 例）レビュー効率の改善
      ・ 例）グラフ描画機能のUI追加
  - type: dropdown
    id: scope
    attributes:
      label: 対応領域
      description: このタスクが属する領域を選択してください
      options:
        - Frontend
        - BackEnd (API Gateway)
        - BackEnd (Agent-Runner)
        - Infra
        - Documents
        - Other
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: 依存する Issue
      description: 先に解決しないと進められない Issue があれば記入してください（例： ＃1234）
  - type: checkboxes
    id: todos
    attributes:
      label: やること
      options:
        - label: 例） API の実装， UI の更新 等
    validations:
      required: true
  - type: textarea
    id: dod
    attributes:
      label: 達成基準
      description: 客観的に確認可能な基準を書いてください
      placeholder: 〈「これができていれば完成」というものを書く〉
    validations:
      required: true
  - type: textarea
    id: outofscope
    attributes:
      label: やらなかったこと（今後やると良さそうなこと）

